### ISSUE TITLE
Provide an example using VS2015 or C#

### ISSUE THREAD

**Issue by cleytonb** [Bkmz21/CompactCNNCascade#1]
Hi,

I'm trying to compile your example but I'm having no success with it. The linker is giving me the error "mismatch detected for '_MSC_VER': value '1800' doesn't match value '1900' in bgs.obj". I believe you're using VS 2012 right?

Can you update to use VS 2015 or a C# example?

**Comment by Bkmz21** [comment]
Hi,

Library build in VS2015.
You compiling CompactCNNCascade/examples/Test.sln? (It does not contain a bgs.cpp)
Just open Test.sln in VS2015, it must be compiled.
