### ISSUE TITLE
Direct GPU Memory Parameter For Detection

### ISSUE THREAD

**Issue by mfbayraktar** [Bkmz21/CompactCNNCascade#4]
Can you add a support to cudeviceptr?
As you know FaceDetector::ImageData accepts CPU data pointer. If you add support GPU data parameter then we use already exist GPU data parameter. OpenCv cvtColor use CPU but with Nvidia performance primvites (npp) we can use GPU for color to grayscale convert process. And then without download GPU data to CPU directly call your face detection function. I think you must add cuda stream support for call asynchronously.

**Comment by Bkmz21** [comment]
Hi,
Just pass the pointer to the color image. Color conversion and resizing image will be executed on the GPU.

**Comment by Bkmz21** [comment]
By default, three cuda streams are used to process the pyramid levels. This library is not thread-safe (GPU implementation only). All calls of method Detect from different threads will be executed sequentially.

**Comment by mfbayraktar** [comment]
In my project scenerio after detection, gray scale image will be use for feature extraction. CompactCNNLibrary may accept color image but does not output grayscale. So we need reconvert image. Can we solve this? I can help CompactCNNLibrary to be thread safe and to be accept GPU device pointer.

**Comment by mfbayraktar** [comment]
I can send sample code about the issue?

**Comment by Bkmz21** [comment]
It would be nice. I'll solve this problem in a couple of days.

**Comment by Bkmz21** [comment]
Hi,
I added the getGrayImage32F function. It allows you to get a pointer to the grayscale data on host or device.
