### ISSUE TITLE
MacOS x & Linux version source

### ISSUE THREAD

**Issue by MyraBaba** [Bkmz21/CompactCNNCascade#5]
Hi,

Can we have compileable sources for MacOSX (Clion) cmake ?

I would like to examine on it as part of my projects.

Best

**Comment by Bkmz21** [comment]
Hi!
Уou can get the source code under a commercial license.

**Comment by MyraBaba** [comment]
how we can test before took the source code ? We are at mac / linux . environment

**Comment by Bkmz21** [comment]
maybe so https://askubuntu.com/questions/187424/install-windows-7-through-virtual-box
