### ISSUE TITLE
No Makefile? No Linux support?

### ISSUE THREAD

**Issue by jhallard** [Bkmz21/CompactCNNCascade#6]
Thank you for taking the time to implement this but the fact that it only comes with pre-compiled binaries and no Makefile means it is hard to get it running on our own. Is there any plan to add a Makefile or instructions on how to build the project?

**Comment by MyraBaba** [comment]
Any update for this ? How we can test and use it ?

**Comment by lucasjinreal** [comment]
It can not test. Just some windows dlls,,,,,,,,,,

**Comment by Bkmz21** [comment]
Source codes are now available. You can build project for Linux using CMake.
